feat: Add support for sourceTypeOverride and sourceLocationOverride
aws-actions/aws-codebuild-run-build pull request #165
Opened 2024-04-28 10:51 UTC by yamao-latte

This commit introduces two new optional parameters:

sourceTypeOverride: Allows overriding the source input type defined in the build project for the current build. Valid values include NO_SOURCE, CODECOMMIT, CODEPIPELINE, GITHUB, S3, BITBUCKET, and GITHUB_ENTERPRISE.
sourceLocationOverride: Enables specifying a location that overrides the source location defined in the build project for the current build.

These parameters provide flexibility in customizing the source settings for individual builds, without modifying the underlying build project configuration.

Issue #164 

*Description of changes:*
- Added `sourceTypeOverride` parameter to allow users to override the source input type defined in the build project.
  - Updated the `action.yml` file to include the `sourceTypeOverride` parameter with a description and set it as optional.
  - Modified the relevant code sections to handle the `sourceTypeOverride` parameter and pass its value to the CodeBuild API when starting a build.
- Introduced `sourceLocationOverride` parameter to enable users to specify a custom source location for the current build.
  - Updated the `action.yml` file to include the `sourceLocationOverride` parameter with a description and set it as optional.
  - Modified the relevant code sections to handle the `sourceLocationOverride` parameter and pass its value to the CodeBuild API when starting a build.
- Updated the README.md file to document the new `sourceTypeOverride` and `sourceLocationOverride` parameters, providing examples and explaining their usage.

These changes enhance the flexibility and usability of the Action, allowing users to customize their build source settings on a per-build basis and enabling integration with various source providers, including GitHub Enterprise.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

# Check any applicable:
- [ ] Were any files moved? Moving files changes their URL, which breaks all hyperlinks to the files.

2024-05-09 07:37 UTC, natanaelfiorilla-scopely commented
Please, review this PR.

2024-06-05 14:58 UTC, kadeboer approved these changes
I could also really use this, and it looks sound to me.

2024-06-24 17:21 UTC, avx-rodmans commented
I need this as well

2024-09-04 19:59 UTC, taoyong-ty commented
Thanks for making this change! taking a look now

2024-09-04 20:04 UTC, taoyong-ty requested changes

2024-09-04 20:04 UTC, taoyong-ty commented on code-build.js
> +
These two new attributes need to be added to the returned struct [here](https://github.com/aws-actions/aws-codebuild-run-build/blob/main/code-build.js#L258-L275)

2024-09-04 20:04 UTC, taoyong-ty commented on code-build.js
> +        sourceLocationOverride: sourceLocationOverride || `https://github.com/${owner}/${repo}.git`,
could you please add an unit test ? 

you can find an example here: https://github.com/aws-actions/aws-codebuild-run-build/blob/main/test/code-build-test.js#L410-L421

2024-09-10 19:16 UTC, taoyong-ty approved these changes

2024-09-10 22:43 UTC, taoyong-ty approved these changes

2024-09-10 22:43 UTC, merged